[frontend]
20.220.191.102

[backend]
20.151.172.142

[all:vars]
ansible_user=kalu
ansible_ssh_private_key_file=~/.ssh/epicbook-key
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
